"""add hero status

Revision ID: 67e3b649400d
Revises: e83d1851d715
Create Date: 2026-10-08 16:29:07.409695

"""
import sqlmodel
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67e3b649400d'
down_revision: Union[str, Sequence[str], None] = 'e83d1851d715'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    status_enum = sa.Enum('active', 'inactive', name='herostatus')
    status_enum.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('status', sa.Enum('active', 'inactive', name='herostatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hero', 'status')
    # ### end Alembic commands ###
    status_enum = sa.Enum('active', 'inactive', name='herostatus')
    status_enum.drop(op.get_bind(), checkfirst=True)